apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pipedreams-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pipedreams-deployment
  minReplicas: 2
  maxReplicas: 5  # Adjust based on the expected load
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Target average CPU utilization for scaling
